---
# Configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

linters:
  # https://golangci-lint.run/usage/configuration/#linters-configuration
  default: all

  # explicitly disabled linters
  disable:
    - depguard
    - exhaustruct
    - gochecknoglobals  # no configuration options
    - nlreturn  # redundant with wsl
    - paralleltest
    - revive
    - thelper
    - varnamelen
    - testableexamples
    - wrapcheck

  settings:
    cyclop:
      max-complexity: 12

    funlen:
      lines: 80
      statements: 60
      ignore-comments: true

    gomoddirectives:
      replace-local: true

    ireturn:
      allow:
        - error
        - generic
        - context.Context
        - credentials.TransportCredentials
        - http.Handler
        - grpc.ClientConnInterface
        - grpc.DialOption
        - middleware.Identity

    lll:
      line-length: 150

    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
