---
# Configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

linters:
  # https://golangci-lint.run/usage/configuration/#linters-configuration
  default: all

  # explicitly disabled linters
  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - nlreturn          # redundant with wsl
    - noinlineerr
    - paralleltest
    - revive
    - thelper
    - varnamelen
    - testableexamples
    - wrapcheck
    - wsl

  settings:
    cyclop:
      max-complexity: 12

    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - os.Close

    funlen:
      lines: 80
      statements: 60
      ignore-comments: true

    gomoddirectives:
      replace-local: true

    gosec:
      excludes:
        - G104  # Errors unhandled
        - G304  # Potential file inclusion via variable (see https://github.com/golang/go/issues/67002)

    ireturn:
      allow:
        - error
        - empty
        - stdlib
        - generic
        - proto.Message
        - credentials.TransportCredentials
        - http.Handler
        - grpc.ClientConnInterface
        - grpc.DialOption
        - middleware.Identity

    lll:
      line-length: 150

    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake

              
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2 

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
